In [1]:
# Import Numpy & PyTorch
import numpy as np
import torch

## Linear Regression Model using PyTorch built-ins

Let's re-implement the same model using some built-in functions and classes from PyTorch.

And now using two different targets: Apples and Oranges

In [2]:
# Imports
import torch.nn as nn

In [3]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

### Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [5]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [6]:
# Define dataset
dataset = TensorDataset(inputs, targets)
dataset[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [7]:

# Define data loader
batch_size = 5
DL = DataLoader(dataset, batch_size, shuffle=True)
next(iter(DL))

[tensor([[ 69.,  96.,  70.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[103., 119.],
         [103., 119.],
         [ 56.,  70.],
         [ 81., 101.],
         [119., 133.]])]

### nn.Linear
Instead of initializing the weights & biases manually, we can define the model using `nn.Linear`.

In [8]:
# Define model
final_model = nn.Linear(3, 2)
print(final_model.weight, end="\n---------\n")
print(final_model.bias)

Parameter containing:
tensor([[ 0.2410,  0.0927,  0.2201],
        [-0.0681,  0.5050,  0.3211]], requires_grad=True)
---------
Parameter containing:
tensor([ 0.4477, -0.3822], requires_grad=True)


### Optimizer
Instead of manually manipulating the weights & biases using gradients, we can use the optimizer `optim.SGD`.

In [9]:
# Define optimizer
opt = torch.optim.SGD(final_model.parameters(), lr=1e-5)

### Loss Function
Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [10]:
# Import nn.functional
import torch.nn.functional as F

In [11]:
# Define loss function
loss_fn = F.mse_loss

In [12]:
loss = loss_fn(final_model(inputs) , targets)
print(loss)

tensor(1941.3541, grad_fn=<MseLossBackward>)


### Train the model

We are ready to train the model now. We can define a utility function `fit` which trains the model for a given number of epochs.

In [13]:
# Define a utility function to train the model
def fit(num_epochs, final_model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in DL:
            # Generate predictions
            pred = final_model(xb)
            loss = loss_fn(pred,yb)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ', loss_fn(final_model(inputs), targets))


In [14]:

# Train the model for 100 epochs
fit(100 , final_model , loss_fn, opt)

Training loss:  tensor(17.1124, grad_fn=<MseLossBackward>)


In [15]:

# Generate predictions
preds = final_model(inputs)
preds

tensor([[ 58.5846,  71.0958],
        [ 81.5533,  98.6889],
        [117.8931, 136.6940],
        [ 28.7413,  41.3128],
        [ 96.4016, 113.0720],
        [ 58.5846,  71.0958],
        [ 81.5533,  98.6889],
        [117.8931, 136.6940],
        [ 28.7413,  41.3128],
        [ 96.4016, 113.0720],
        [ 58.5846,  71.0958],
        [ 81.5533,  98.6889],
        [117.8931, 136.6940],
        [ 28.7413,  41.3128],
        [ 96.4016, 113.0720]], grad_fn=<AddmmBackward>)

In [16]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Now we can define the model, optimizer and loss function exactly as before.

In [17]:
fit(100 , final_model , loss_fn, opt)

Training loss:  tensor(5.5080, grad_fn=<MseLossBackward>)


## Exercise 1:
 Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want)
 
 
## Exercise 2:
 Try Linear regression on same prediction data using Tensorflow

 

In [18]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

x_shape = inputs.shape

In [19]:

# weights and biases
weights = np.random.rand(2,3)
biases = np.random.rand(15,2)
print("Weights:",weights,sep='\n')
print("Biases:",biases,sep="\n")

Weights:
[[0.04434255 0.38897932 0.53830319]
 [0.13255347 0.43567721 0.33309745]]
Biases:
[[0.1484719  0.96984244]
 [0.67358485 0.50747122]
 [0.64699587 0.72921251]
 [0.3064264  0.65087561]
 [0.97770648 0.57159369]
 [0.84436029 0.74716892]
 [0.9855936  0.23312284]
 [0.11325332 0.50405813]
 [0.12989206 0.4028688 ]
 [0.45857084 0.84849663]
 [0.7901087  0.45161009]
 [0.08587349 0.16546801]
 [0.57687987 0.55179487]
 [0.76253231 0.68899551]
 [0.52030998 0.1985776 ]]


In [20]:
# Define the model
def model(x):
    return x @ np.transpose(weights) + biases

In [21]:

# Generate predictions
preds = model(inputs)

In [22]:
# Compare with targets
print("Predictions : ", preds, sep="\n")
print("Targets : ",targets, sep="\n")

Predictions : 
[[52.59413002 54.15980924]
 [73.39034171 72.22766839]
 [87.84961193 89.96176264]
 [41.47269582 45.23005535]
 [79.06058084 74.8596169 ]
 [53.29001841 53.93713573]
 [73.70235045 71.95332001]
 [87.31586938 89.73660826]
 [41.29616148 44.98204854]
 [78.5414452  75.13651984]
 [53.23576682 53.6415769 ]
 [72.80263035 71.88566518]
 [87.77949593 89.784345  ]
 [41.92880173 45.26817525]
 [78.60318434 74.48660081]]
Targets : 
[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [23]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return np.sum(diff * diff) / len(diff)

In [24]:
# Compute loss
loss = mse(preds, targets)
print(loss)

1400.6708077743344


In [25]:
# compute gradients
biases_grad = (preds-targets)*2/x_shape[0]
weights_grad = (np.matmul(np.transpose((preds-targets)),inputs))*2/x_shape[0]

print("weights_grad:",weights_grad, sep="\n")
print("biases_grad:",biases_grad, sep="\n")

weights_grad:
[[-1329.23174423 -2626.11344173 -1365.27416181]
 [-3913.16383743 -5321.06330414 -3136.18910018]]
biases_grad:
[[-0.454116   -2.11202543]
 [-1.01462111 -3.83631088]
 [-4.15338508 -5.73843165]
 [ 2.59635944  1.09734071]
 [-3.19192256 -5.88538441]
 [-0.36133088 -2.14171524]
 [-0.97301994 -3.87289066]
 [-4.22455075 -5.76845223]
 [ 2.57282153  1.06427314]
 [-3.26114064 -5.84846402]
 [-0.36856442 -2.18112308]
 [-1.09298262 -3.88191131]
 [-4.16273388 -5.76208733]
 [ 2.65717356  1.10242337]
 [-3.25290876 -5.93511989]]


Adjust weights

In [26]:
# Adjust weights
weights -= weights_grad * 1e-5
biases -= biases_grad * 1e-5

In [27]:
print("Weights:",weights,sep='\n')
print("Biases:",biases,sep="\n")

Weights:
[[0.05763487 0.41524045 0.55195594]
 [0.17168511 0.48888784 0.36445935]]
Biases:
[[0.14847644 0.96986356]
 [0.673595   0.50750958]
 [0.6470374  0.72926989]
 [0.30640043 0.65086464]
 [0.9777384  0.57165254]
 [0.84436391 0.74719034]
 [0.98560333 0.23316157]
 [0.11329557 0.50411582]
 [0.12986634 0.40285816]
 [0.45860345 0.84855511]
 [0.79011238 0.4516319 ]
 [0.08588442 0.16550683]
 [0.5769215  0.55185249]
 [0.76250574 0.68898449]
 [0.52034251 0.19863695]]


In [28]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

873.160924022737


In [29]:
# repeating same for 200 times
for i in range(200):
    preds = model(inputs)
    loss = mse(preds, targets)
    
    biases_grad = ((((inputs@np.transpose(weights))+biases)-targets))*2/x_shape[0]
    weights_grad = (np.matmul(np.transpose((((inputs@np.transpose(weights))+biases)-targets)),inputs))*2/x_shape[0]

    weights -= weights_grad * 1e-5
    biases -= biases_grad * 1e-5

In [30]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

15.195321686791628


In [31]:
# Print predictions
print(preds)

[[ 57.31285048  71.46967451]
 [ 82.27927569  98.59176342]
 [118.10152011 136.63075028]
 [ 23.39365902  40.59149012]
 [100.87130825 113.69396378]
 [ 58.0085524   71.24706067]
 [ 82.59120083  98.31748855]
 [117.56792059 136.40565623]
 [ 23.217172    40.34354977]
 [100.35231172 113.97079252]
 [ 57.95431534  70.95158103]
 [ 81.69172181  98.24985185]
 [118.03142291 136.45338018]
 [ 23.84964271  40.62959981]
 [100.41403432 113.32104765]]


In [32]:
# Print targets
print(targets)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]
